services:
  db:
    image: postgres:14-alpine
    container_name: librishare-db
    environment:
      POSTGRES_DB: librishare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - librishare-network

  app:
    build: .
    container_name: librishare-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librishare
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - librishare-network

  frontend:
    container_name: librishare-frontend
    build:
      context: ../../libri-share-front-end/librishare
      dockerfile: Dockerfile
      # --- ADICIONE ESTA LINHA 'args' ---
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - librishare-network
    depends_on:
      - app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

volumes:
  postgres_data:

networks:
  librishare-network:
    driver: bridge